name: Feature request
description: Suggest a new feature or enhancement for the package
title: "[FEATURE] Brief description of the feature"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Please complete all fields below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: What problem are you facing?
      description: Describe the problem you’re trying to solve.
      placeholder: "A clear description of the issue or use case."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like to see.
      placeholder: "A clear and concise description of the desired feature."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative approaches
      description: Any alternative solutions you’ve considered.
      placeholder: "Other approaches you've tried or considered."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots here.
      placeholder: "Any other details to help us."
    validations:
      required: false
